// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy-f7d0NpuOVK1PNQC52MF5_2kQCePvTU',
    appId: '1:124407712666:web:032893243df7cdfa0b0823',
    messagingSenderId: '124407712666',
    projectId: 'hiwhub-df6e6',
    authDomain: 'hiwhub-df6e6.firebaseapp.com',
    storageBucket: 'hiwhub-df6e6.appspot.com',
    measurementId: 'G-ERQ123JF9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgGiccK7VGNw0XqGDtCebBcbIQBBY_9I',
    appId: '1:124407712666:android:60d48110cb9569fd0b0823',
    messagingSenderId: '124407712666',
    projectId: 'hiwhub-df6e6',
    storageBucket: 'hiwhub-df6e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL-6cqA32LbDGyS2Uz4jV_rrGr7fg9-SY',
    appId: '1:124407712666:ios:178156cf921bab170b0823',
    messagingSenderId: '124407712666',
    projectId: 'hiwhub-df6e6',
    storageBucket: 'hiwhub-df6e6.appspot.com',
    iosClientId: '124407712666-cf0t1mhfa7it9ngirdkku8mf6esgnkf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectIce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL-6cqA32LbDGyS2Uz4jV_rrGr7fg9-SY',
    appId: '1:124407712666:ios:178156cf921bab170b0823',
    messagingSenderId: '124407712666',
    projectId: 'hiwhub-df6e6',
    storageBucket: 'hiwhub-df6e6.appspot.com',
    iosClientId: '124407712666-cf0t1mhfa7it9ngirdkku8mf6esgnkf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectIce',
  );
}
